import { Router, Request, Response } from 'express'
import { authMiddleware } from '../middleware/auth.middleware'
import { agentCollaborationService } from '../services/agent-collaboration.service'

const router = Router()

/**
 * 1. GET /api/collaboration/teams/:teamId/live
 * Fetches real-time inter-agent group chat feed for a team squad.
 */
router.get('/teams/:teamId/live', authMiddleware, (req: Request, res: Response) => {
  const { teamId } = req.params
  const limit = req.query.limit ? parseInt(req.query.limit as string, 10) : 50
  const chatter = agentCollaborationService.getLiveTeamChatter(teamId, limit)
  res.json({ success: true, teamId, messages: chatter })
})

/**
 * 2. GET /api/collaboration/runs/:runId/timeline
 * Fetches structured collaboration timeline (handoffs, escalations, standups) for a mission run.
 */
router.get('/runs/:runId/timeline', authMiddleware, (req: Request, res: Response) => {
  const { runId } = req.params
  const timeline = agentCollaborationService.getRunCollaborationTimeline(runId)
  res.json({ success: true, runId, ...timeline })
})

/**
 * 3. POST /api/collaboration/runs/:runId/handoff
 * Executes a structured handoff from one agent role to another.
 */
router.post('/runs/:runId/handoff', authMiddleware, async (req: Request, res: Response) => {
  const { runId } = req.params
  const { teamId, fromRole, toRole, summaryOfWorkDone, keyContextForReceiver, artifactsProduced = [], openQuestions = [] } = req.body

  if (!teamId || !fromRole || !toRole || !summaryOfWorkDone) {
    return res.status(400).json({ error: 'teamId, fromRole, toRole, and summaryOfWorkDone are required' })
  }

  const handoff = await agentCollaborationService.performHandoff({
    runId,
    teamId,
    fromRole,
    toRole,
    summaryOfWorkDone,
    keyContextForReceiver: keyContextForReceiver || {},
    artifactsProduced,
    openQuestions,
  })

  res.json({ success: true, handoff })
})

/**
 * 4. POST /api/collaboration/runs/:runId/escalate
 * Submits an escalation from an agent to TeamLead or Human Operator.
 */
router.post('/runs/:runId/escalate', authMiddleware, async (req: Request, res: Response) => {
  const { runId } = req.params
  const { teamId, fromRole, escalationTarget = 'team_lead', blockerReason, attemptedApproaches = [], requiredDecision, urgency = 'high' } = req.body

  if (!teamId || !fromRole || !blockerReason || !requiredDecision) {
    return res.status(400).json({ error: 'teamId, fromRole, blockerReason, and requiredDecision are required' })
  }

  const escalation = await agentCollaborationService.escalateIssue({
    runId,
    teamId,
    fromRole,
    escalationTarget,
    blockerReason,
    attemptedApproaches,
    requiredDecision,
    urgency,
  })

  res.json({ success: true, escalation })
})

/**
 * 5. POST /api/collaboration/runs/:runId/escalate/:id/resolve
 * Resolves an active escalation with decision or feedback.
 */
router.post('/runs/:runId/escalate/:id/resolve', authMiddleware, (req: Request, res: Response) => {
  const { runId, id } = req.params
  const { resolution, resolvedBy = 'human_supervisor' } = req.body

  if (!resolution) {
    return res.status(400).json({ error: 'resolution is required' })
  }

  const resolved = agentCollaborationService.resolveEscalation(runId, id, resolution, resolvedBy)
  if (!resolved) {
    return res.status(404).json({ error: 'Escalation not found' })
  }

  res.json({ success: true, escalation: resolved })
})

/**
 * 6. POST /api/collaboration/runs/:runId/standup
 * Triggers a team standup summary generated by TeamLead.
 */
router.post('/runs/:runId/standup', authMiddleware, async (req: Request, res: Response) => {
  const { runId } = req.params
  const { teamId, teamLeadRole = 'team_lead', summaryHeadline, whatIsDone = [], whatIsInProgress = [], whatIsBlocked = [], estimatedProgressPercent = 50 } = req.body

  if (!teamId || !summaryHeadline) {
    return res.status(400).json({ error: 'teamId and summaryHeadline are required' })
  }

  const standup = await agentCollaborationService.generateStandupSummary({
    runId,
    teamId,
    teamLeadRole,
    summaryHeadline,
    whatIsDone,
    whatIsInProgress,
    whatIsBlocked,
    estimatedProgressPercent,
  })

  res.json({ success: true, standup })
})

/**
 * 7. POST /api/collaboration/runs/:runId/clarify
 * Executes inter-agent clarifying Q&A with turn limit and loop protection.
 */
router.post('/runs/:runId/clarify', authMiddleware, async (req: Request, res: Response) => {
  const { runId } = req.params
  const { conversationId, teamId, fromRole, toRole, question, answer, handoffId, maxRounds = 3 } = req.body

  if (answer && conversationId) {
    // Replying to existing question
    const updated = await agentCollaborationService.respondClarification({
      conversationId,
      fromRole,
      answer,
    })
    return res.json({ success: true, exchange: updated })
  }

  if (!teamId || !fromRole || !toRole || !question) {
    return res.status(400).json({ error: 'teamId, fromRole, toRole, and question are required' })
  }

  const result = await agentCollaborationService.askClarification({
    runId,
    teamId,
    handoffId,
    fromRole,
    toRole,
    question,
    maxRounds,
  })

  res.json({ success: true, ...result })
})

export default router
